### ISSUE TITLE
After the user takes a picture and chooses to retake it, they cannot use flash or flip direction the camera is facing

### ISSUE THREAD

**Issue by KileyCaravella** [miller-ms/MMSProfileImagePicker#1]
### Expected Behavior

a user should be able to toggle the flash and the camera's direction whenever they attempt to take a photo.
### Actual Behavior

These can only be changed when the user initially takes a photo. Any other time and the buttons are inoperable
### Steps to Reproduce
1. take a photo
2. press "retake" on next screen
3. attempt to flip the camera or toggle the flash
### Note to Creator

I believe this may be due to the status bar being set to hidden when the user is in the "crop image" view. The status bar disappears while the user is cropping the image, and returns in the camera but is unusable. Furthermore, when the user returns to the application that is using the pod, the status bar is hidden as well.

**Comment by miller-ms** [comment]
Thank you for reporting this. I'm working on a solution.

**Comment by miller-ms** [comment]
This is corrected in version 1.2.1.
