### ISSUE TITLE
Property 'delegate' not found on object of type 'MMSCameraViewController *'

### ISSUE THREAD

**Issue by jstngoulet** [miller-ms/MMSProfileImagePicker#10]
### Expected Behavior
Property is assigned as open and should be accruable within the MMSProfileImagePicker class.

### Actual Behavior
Build error, on line 847 of MMSProfileImagePicker, noting that the delegate property cannot be found.

### Steps to Reproduce
Build pod project within parent project.

**Comment by miller-ms** [comment]
Hi Justin, thanks for the defect report.   This is building correctly from the 1.5.0 tag.  Is it possible you need to run pod update?

**Comment by jstngoulet** [comment]
Sure thing. Just ran `pod update` on my existing project, and it noted that 1.4.1 was the most recent version. I tried explicitly stating the version to 1.5 as well as implicitly updating (Without the version number in the pod file).

In addition, I tried a clean install of the pod into a new project, and 1.4.1 was still the most recent version. I know you stated 1.5 was released in your release notes, but I am not sure how long / what needs to be done to be recognized.

**Comment by miller-ms** [comment]
Justin, I'm unsure of what is going on for you, but I went to cocoapods.org, and 1.5.0 is indeed the latest version available.  That's the version needed to correct this problem.

**Comment by miller-ms** [comment]
Justin, I made a successful pod install with a pod file that looks as follows:

use_frameworks!

target 'profiletest' do
pod 'MMSProfileImagePicker', '~> 1.5'
end

**Comment by jstngoulet** [comment]
Looking into this further. Will update on progress. Thanks for your prompt replies!

**Comment by jstngoulet** [comment]
Hmm. Have you seen this issue before? 
```Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `MMSProfileImagePicker (~> 1.5)` required by `Podfile`

Specs satisfying the `MMSProfileImagePicker (~> 1.5)` dependency were found, but they required a higher minimum deployment target.```

**Comment by miller-ms** [comment]
I upgraded all the deployment targets to 9.0.  I saw something like this when I had the following in a pod file.

platform :ios, '8.3'

if you have something like. that. Make it 9.0.

**Comment by jstngoulet** [comment]
Tha'd be it. It was set to 8.0. I have upgraded my project accordingly and am testing the updated pod now. Thanks for your help!

**Comment by miller-ms** [comment]
Glad to hear.  And thanks for reporting defects.
