### ISSUE TITLE
Edit Controller Not Appearing

### ISSUE THREAD

**Issue by AlexFWulff** [miller-ms/MMSProfileImagePicker#12]
I am utilizing the following code to call the profile picker in iOS 11 and Swift 4.0:

```
@IBAction func pickPhotoPress(_ sender: AnyObject) {
        let optionMenu = UIAlertController(title: nil, message: "Choose Option", preferredStyle: .actionSheet)
        let profilePicker = MMSProfileImagePicker.init()
        profilePicker.delegate = self
        
        let cameraAction = UIAlertAction(title: "Camera", style: .default, handler: {
            (alert: UIAlertAction!) -> Void in
            
            profilePicker.select(fromCamera: self)
        })
        
        let galleryAction = UIAlertAction(title: "Gallery", style: .default, handler: {
            (alert: UIAlertAction!) -> Void in
            
            profilePicker.select(fromPhotoLibrary: self)
        })
        
        
        optionMenu.addAction(cameraAction)
        optionMenu.addAction(galleryAction)
        
        self.present(optionMenu, animated: true, completion: nil)
    }
```

The gallery appears correctly, but when I select an image the whole picker UI disappears and no UI to edit the image with a mask is ever called. `didFinishPickingMediaWithInfo` is also never called.

Is there some way to fix this issue?

**Comment by miller-ms** [comment]
You are instantiating profile picker as a local variable inside of pickPhotoPress:

`let profilePicker = MMSProfileImagePicker.init()`

By the time the action is called to select from the photo library, the local variable profilePicker has been deallocated.  All of these interactions are asynchronous and you have to write the code to support that. 

Making  profilePicker a member variable of the view controller is probably what you want.

**Comment by miller-ms** [comment]
Closing assuming the earlier response corrected your problem.
