### ISSUE TITLE
MMSCameraViewController version issue

### ISSUE THREAD

**Issue by emreoktem** [miller-ms/MMSProfileImagePicker#14]
Hi, 

Current version supports up to v1.2.1 of MMSCameraViewController as given in the podspec

s.dependency 'MMSCameraViewController',  '~> 1.2.1'

The version should be updated because it's not possible to get the current updates of MMSCameraViewController if you are using cocoapods. (for example iPhoneX support fixes of MMSCameraViewController, etc...)

Thanks in advance.

**Comment by miller-ms** [comment]
Hi, This has been corrected in version 1.6.0
