### ISSUE TITLE
MMSCameraViewController has old swift version code

### ISSUE THREAD

**Issue by Rjmaurya13** [miller-ms/MMSProfileImagePicker#15]
Hi,

I am getting issue in the MMSCameraViewController file.

Here is the screenshot1. 

![screen shot 2019-02-05 at 6 46 36 pm](https://user-images.githubusercontent.com/1842897/52275825-9d183580-2976-11e9-908d-3e965fb7b9c4.png)

Here is the screenshot2.
 
![screen shot 2019-02-05 at 6 46 45 pm](https://user-images.githubusercontent.com/1842897/52275826-9d183580-2976-11e9-8b91-8ac11ef8b570.png)

There are other issues as well.

**Comment by miller-ms** [comment]
I updated pod MMSCameraViewController to support swift 4.2 and resubmitted this pod to work with the new version. You should be good now with MMSProfileImagePicker 1.6.0

**Comment by Rjmaurya13** [comment]
Hi, It looks like you haven't merged this code to master. Below are the version of branch.
MMSCameraViewController (1.2.1)
MMSProfileImagePicker (1.5.1)
