### ISSUE TITLE
UIDeviceOrientationDidChange' has been renamed to 'UIDevice.orientationDidChangeNotification'

### ISSUE THREAD

**Issue by Rjmaurya13** [miller-ms/MMSProfileImagePicker#18]
UIDeviceOrientationDidChange' has been renamed to 'UIDevice.orientationDidChangeNotification'
Replace 'UIDeviceOrientationDidChange' with 'UIDevice.orientationDidChangeNotification'

**Comment by daniestrella1** [comment]
Some news about this issue?

**Comment by miller-ms** [comment]
this was closed with 1.6.0.
