### ISSUE TITLE
Terminating app due to uncaught exception 'CALayerInvalidGeometry'

### ISSUE THREAD

**Issue by takasurazeem** [miller-ms/MMSProfileImagePicker#21]
### Expected Behavior
Show the image picker
### Actual Behavior
crashes
### Steps to Reproduce
```
@IBAction func selectProfilePictureWasTapped(_ sender: UIButton) {
        let profileImagePicker = MMSProfileImagePicker()
        profileImagePicker.delegate = self
        present(profileImagePicker, animated: true)
    }
```

###Log:
2021-04-07 14:10:40.695732+0500 Coda Music[8591:22770448] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [207 nan]. Layer: <CALayer:0x600001427dc0; position = CGPoint (0 0); bounds = CGRect (0 0; 0 0); delegate = <UIImageView: 0x7f94efa15f90; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CALayer: 0x600001427dc0>>; opaque = YES; allowsGroupOpacity = YES; >'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001094feaf6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010938ee78 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001094fe9d4 -[NSException initWithCoder:] + 0
	3   QuartzCore                          0x00000001082fb6ab _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 187
	4   QuartzCore                          0x00000001082e85e6 -[CALayer setPosition:] + 49
	5   QuartzCore                          0x00000001082e8c71 -[CALayer setFrame:] + 542
	6   UIKitCore                           0x00000001158412f8 -[UIView(Geometry) setFrame:] + 431
	7   UIKitCore                           0x0000000115809923 -[UIImageView _setViewGeometry:forMetric:] + 153
	8   MMSProfileImagePicker               0x00000001080e315c -[MMSProfileImagePicker positionImageView] + 556
	9   MMSProfileImagePicker               0x00000001080e2986 -[MMSProfileImagePicker viewWillAppear:] + 86
	10  UIKitCore                           0x0000000114bcfc66 -[UIViewController _setViewAppearState:isAnimating:] + 654
	11  UIKitCore                           0x0000000114bd048f -[UIViewController __viewWillAppear:] + 106
	12  UIKitCore                           0x0000000114aa51c3 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.466 + 1201
	13  UIKitCore                           0x00000001157f807a -[_UIAfterCACommitBlock run] + 54
	14  UIKitCore                           0x000000011530c954 _runAfterCACommitDeferredBlocks + 333
	15  UIKitCore                           0x00000001152fc9fc _cleanUpAfterCAFlushAndRunDeferredBlocks + 221
	16  UIKitCore                           0x000000011532e2ac _afterCACommitHandler + 85
	17  CoreFoundation                      0x000000010946c1f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	18  CoreFoundation                      0x0000000109466a77 __CFRunLoopDoObservers + 547
	19  CoreFoundation                      0x000000010946701a __CFRunLoopRun + 1113
	20  CoreFoundation                      0x00000001094666d6 CFRunLoopRunSpecific + 567
	21  GraphicsServices                    0x000000010d1a7db3 GSEventRunModal + 139
	22  UIKitCore                           0x00000001152fdcf7 -[UIApplication _run] + 912
	23  UIKitCore                           0x0000000115302ba8 UIApplicationMain + 101
	24  Coda Music                          0x00000001055e277b main + 75
	25  libdyld.dylib                       0x000000010aca83e9 start + 1
	26  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Signal: SIGABRT (signal SIGABRT)

**Comment by miller-ms** [comment]
`let profileImagePicker = MMSProfileImagePicker()`
Is no longer allocated when the function `selectProfilePictureWasTapped` exits, but the `MMSProfileImagePicker`'s `UIViewController` and its view are in the process of showing. One way to solve this is to make `profileImagePicker` a property of the class.  Local variables are on the stack and only live as long as the lines of the function are executing. 'present(profileImagePicker, animated: true)` executes asynchronously to the code that starts it's presentation.
