### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by rbeeger** [miller-ms/MMSProfileImagePicker#3]
### Expected Behavior

it should be possible to include the framework as a dependency via Carthage
### Actual Behavior

Carthage cannot build MMSProfileImagePicker
### Steps to Reproduce

Include 
github "miller-ms/MMSProfileImagePicker" == 1.1.0
in a Cartfile. run carthage bootstrap

**Comment by miller-ms** [comment]
fixed in release 1.3.1
