### ISSUE TITLE
Carthage module MMSProfileImagePicker references MMSCameraViewController

### ISSUE THREAD

**Issue by rbeeger** [miller-ms/MMSProfileImagePicker#4]
### Expected Behavior
Building MMSProfileImagePicker from Carthage should only build the main module
### Actual Behavior
Including 
`github "miller-ms/MMSProfileImagePicker" == 1.3.1`
in a Cartfile results in Carthage building the following
```
*** Building scheme "MMSCameraViewController" in MMSProfileImagePicker.xcworkspace
*** Building scheme "FBSnapshotTestCase" in MMSProfileImagePicker.xcworkspace
*** Building scheme "MMSProfileImagePicker" in MMSProfileImagePicker.xcworkspace
```
The bad thing about this is that you cannot use `MMSProfileImagePicker` without also using `MMSCameraViewController` which belongs to an example project that does not interest me when including MMSProfileImagePicker in another app

### Steps to Reproduce
Create a Cartfile with 
`github "miller-ms/MMSProfileImagePicker" == 1.3.1`
Try to just use `MMSProfileImagePicker` in the project containing that Cartfle.
Get the following entry in the log upon launching the app:
```
dyld: Library not loaded: @rpath/MMSCameraViewController.framework/MMSCameraViewController
  Referenced from: /private/var/containers/Bundle/Application/.../Frameworks/MMSProfileImagePicker.framework/MMSProfileImagePicker
  Reason: image not found

```

**Comment by miller-ms** [comment]
The picker requires MMSCameraViewController to work.
