### ISSUE TITLE
Camera fails sometimes before after dismissing controller

### ISSUE THREAD

**Issue by muppetkermit** [miller-ms/MMSProfileImagePicker#5]
### Expected Behavior
Dismiss ImagePickerController and use cropped image in mmsImagePickerController method.
### Actual Behavior
After few try app crashes.
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MMSCameraViewController.MMSCameraViewController 0x10b20f310> for the key path "capturingStillImage" from <AVCaptureStillImageOutput 0x17043cd00> because it is not registered as an observer.'

### Steps to Reproduce
Use ImagePickerController more than one and app crashes. It happen on first time sometimes.

Thanks, have a nice day.

**Comment by miller-ms** [comment]
It's not designed to support more than one. Is that a real use case? What's your purpose for using more than one?

**Comment by ElectroBuddha** [comment]
I can confirm that this issue is still present in iOS 11.2. Dismissing viewcontroller after capturing image sometimes produces a described crash "...it is not registered as an observer"
