### ISSUE TITLE
Crashing when doing multiple camera shots

### ISSUE THREAD

**Issue by ElyDantas** [miller-ms/MMSProfileImagePicker#7]
### Expected Behavior
MMSProfileImagePicker to pick the first image taken and handle multiple shots taken after by the user just so the app don't crash
### Actual Behavior
MMSProfileImagePicker is crashing when user clicks very fast multiple times to take a picture from camera.
### Steps to Reproduce
Just initialize MMSProfileImagePicker for camera `self.profilePicker?.select(fromCamera: self)` and click multiple times to take a camera shot in a small interval of time then the app app will crash.

**Comment by miller-ms** [comment]
Fixed in Version 1.4.1.  Thank you for bringing to my attention.
